### PR TITLE
Swift 3.0

### PR DESCRIPTION
**Pull request by pietbrauer**
I migrated all Xcode projects to latest Swift (3.0.2) which changed no code.

### CODE REVIEW

**Comment by jhudsonWA** [comment]
I'll take a look at this on Monday. The current code is swift3, so I'm assuming this just updates it to use the latest xcode 8 and recompiles to the latest version of Swift3

**Comment by pietbrauer** [comment]
Yes, you are right it is Xcode 8.2 so Swift 3.0.2. Something big seems to have changed in `xctool` though in the Travis Xcode 8.2 image.

**Comment by jhudsonWA** [comment]
I was able to finally fix the Travis 8.x issues. Was due to a major change in Xcode 8. Got the right combination of xcodebuilder commands put together.

**Comment by pietbrauer** [comment]
Glad you found a solution. I wasn't sure if it was ok to switch to `xcodebuild`.

**Comment by jhudsonWA** [comment]
xctool seems to be mostly dead, seems like you almost have to. Finding documentation on Travis though is impossible.

**Pull request merged**
