### PR TITLE
Using the same framework name in Cocoapods and Carthage

### PR DESCRIPTION
**Pull request by cozzin**
Since the framework name is different from the name of the pod, you need to import it with a different name when installing through Carthage.

https://github.com/ZipArchive/ZipArchive/blob/3078747d91537e8c5cea89971bb21e7a1d687d0c/Example/SwiftExample/ViewController.swift#L11-L15

This PR allows you to use same framework name.

```swift
import SSZipArchive // CocoaPods & Carthage
```

### CODE REVIEW

**Comment by Coeur** [comment]
I remember I was told that we should be trying to drop the double `S` if possible, not the other way around.

And maybe this change is superfluous, until we decide for a name for the Swift Packet Manager.

**Comment by cozzin** [comment]
`ZipArchive` pod already has registered.
It seems to be the best keeping now.
You can close this PR if there is no other way.

**Comment by jhudsonWA** [comment]
We do want to drop the SS, but yes cocoapods already had ZipArchive taken. I agree with @Coeur, we can revisit when we decide to adopt Swift PM.

**Comment by Coeur** [comment]
An idea for an alternative, in case we want to keep crediting Sam Soffes, we could use his other prefix, like in: https://github.com/soffes/SAMSoundEffect
That would make SamZipArchive or SAMZipArchive.

**Comment by jhudsonWA** [comment]
I’m not sure we have to keep the credit in the name. We now credit him in the read me. A name change would be appropriate. I think the issue with ZipArchive is it may have already been used in Cocoapods.

**Pull request closed without merging**
