### PR TITLE
Upgrade minizip to 4.0.7

### PR DESCRIPTION
**Pull request by Shebuka**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@Coeur, @Shebuka: Here it is minizip-ng, not minizip.

Can you change the name in the ZipArchive code?
- https://github.com/zlib-ng/minizip-ng
- https://github.com/madler/zlib/tree/develop/contrib/minizip (Included in zlib) from @gvollant.

**Comment by Coeur** [comment]
Not for now. I prefer to keep `minizip` as a folder name for `minizip.c`.
We already refer to minizip-ng in the readme.

**Comment by Shebuka** [comment]
@Coeur I've looked through the code and I don't see any issue with changing of the order in the `unz_global_info` struct. ZipArchive being a wrapper around minizip hides this perfectly.
The only possible problem is if someone uses the struct as a packed memory blob in `zipArchiveWillUnzipArchiveAtPath` and `zipArchiveDidUnzipArchiveAtPath` callbacks, but why should they?

**Comment by Coeur** [comment]
> but why should they?

Well, they should not. If one saves or hashes a structure for later, it should be done exclusively on a structure that they own, to prevent breakage.
But for the same reasons, we should not have exposed a third-party structure like we did to begin with.

I'll discuss it with @jhudsonWA and @willson-chen later. Maybe a ZipArchive 2.7.0 will be enough to alert something is different from previous version. I've already started my own PR at #724 to include also changes to make it safe for App Store.

**Comment by Coeur** [comment]
done with #724

**Pull request closed without merging**
