### PR TITLE
Added support for getting zip file creation progress.

### PR DESCRIPTION
**Pull request by Davidde94**

### CODE REVIEW

**Comment by jhudsonWA** [comment]
I will take a look at this PR on Monday morning. Thanks!

**Comment by jhudsonWA** [comment]
Had to roll back. Tests did not pass once merged in. I saw you changed the main function call to call your new function with a null handler. However, this seems to broke two tests: Example..

screen shot 2017-01-23 at 11 04 59 am

Please update and resubmit with all tests passing and I'll remerge.

**Comment by Davidde94** [comment]
Thanks for pointing this out, I'll investigate and get back to you

**Comment by jhudsonWA** [comment]
Great thanks!

**Comment by Davidde94** [comment]
Sorted, caused by small typo. Everything fixed on my end :)

**Comment by jhudsonWA** [comment]
Thanks. :) I'll remerge in and test

**Pull request merged**
