### PR TITLE
Added support for watchos to the podspec.

### PR DESCRIPTION
**Pull request by jasdeepsaini**

### CODE REVIEW

**Comment by jhudsonWA** [comment]
Did you test this on watch os does it compress and decompress?

**Comment by jasdeepsaini** [comment]
It definitely compresses.  I haven't actually tested decompressing.  I will do that.

**Comment by jhudsonWA** [comment]
No need to close this. I just don't have tests for it, if you got a compress then I'll merge it.

**Comment by jasdeepsaini** [comment]
All right.  I reopened the branch.  Felt like I missed testing a bunch of the functionality when you mentioned decompressing.  I basically made sure I could use it in my watch code and that it would compress a file.

Didn't really test beyond that.

**Comment by jhudsonWA** [comment]
Merged. Thanks for the PR!

**Comment by jhudsonWA** [comment]
I'll create a new pod release soon.

**Pull request merged**
