### PR TITLE
 Added gitaction build

### PR DESCRIPTION
**Pull request by willson-chen**
Added gitaction build and show code coverage.

### CODE REVIEW

**Comment by MoNTE48** [comment]
@jhudsonWA, can this be merged?

**Comment by jhudsonWA** [comment]
Good question. @willson-chen can you confirm this build still works on your fork with any and all GitHub action changes? Plus, we wouldn't really need both travis and actions if adopted as long as the supported features were the same.

**Comment by jhudsonWA** [comment]
I'm going to merge this in, and will eventually be phasing out travis-ci. 

Actions have limitations to our current travis builds (less older version of xcode are supported), but as of 5/31 Travis is phasing out travis-ci.org (which we got unlimited build minutes on) to travis-ci.com. On .com we have to apply for credits and then they give a set amount (we were given 25000). Our issue is with the current setup we will burn through 5000 credits per build. 

Given that, I don't think travis-ci has a future with our project. I'll modify the action to test on as old of versions of xcodes as actions images support, but it won't be back to xcode 7.3 like travis supports now.

**Comment by jhudsonWA** [comment]
https://blog.travis-ci.com/2021-05-07-orgshutdown

**Pull request merged**
