### PR TITLE
Adding support for Swift Package Manager

### PR DESCRIPTION
**Pull request by victor-pavlychko**
- moved public headers to `include/`
- added `Package.swift` matching configuration specified in `SSZipArchive.podspec`
- updated original project to reflect new folder structure
- updated `SSZipArchive.podspec` to reflect new folder structure
- added `.build/` to the ignore list
- removed eXecute permission flag from source files

### CODE REVIEW

**Comment by ryanholden8** [comment]
Looking forward move away from cocoapods to Swift Package manager for this project, thanks for considering! @muizidin @Coeur

**Comment by Fonceur** [comment]
I implemented it by forking from master, and adding back that PR content (to avoid the conflict), it worked fine, though I had to remove **ZipArchive/** from 2 imports.

**Comment by shawnce** [comment]
Any update on moving this work forward?

**Comment by WedgeSparda** [comment]
Also very interested in this MR to be merged? Any update?

**Comment by MoNTE48** [comment]
@willson-chen, can you review and merge this?

**Comment by victor-pavlychko** [comment]
Wow, thanks for the interest to my PR :)

I found ZipArchive’s general approach a bit limited for my needs and ended up moving to [libzip](https://libzip.org/).

Here is a wrapper I built for myself — https://github.com/SwiftZip/SwiftZip. It lacks tests and some proper finish but seems to work fine in my projects.

**Comment by jhudsonWA** [comment]
> @willson-chen, can you review and merge this?

@willson-chen I'm fine with you handling any PR merge if it passes tests, etc. No need to check with @Coeur and myself first. I've been slammed with real life work, but there is a lot of support around supporting SPM, so we should consider it.

**Comment by AndrewSB** [comment]
I've rebased this over at https://github.com/AndrewSB/ZipArchive : master

**Comment by paulja** [comment]
Any news on when this might happen?

**Comment by pitoneux** [comment]
Please ?

**Comment by jhudsonWA** [comment]
@victor-pavlychko What is the purpose of -  moved public headers to include/? Trying to avoid conflicts with other packages or is this a SPM specific change?

**Comment by AndrewSB** [comment]
I believe include is the default location SPM looks for public headers. They can be elsewhere, but you'd need to define a custom path in the Package.swift

**Comment by jhudsonWA** [comment]
> I believe include is the default location SPM looks for public headers. They can be elsewhere, but you'd need to define a custom path in the Package.swift

Ok, let me run some tests to make sure it doesn't break other package managers. Give me a day or two to review.

**Comment by jhudsonWA** [comment]
This PR has been merged into master after I ran tests, etc. Thank you for your patience and @victor-pavlychko thank you for your work on this.

**Comment by Coeur** [comment]
Whoah, finally!

**Comment by MoNTE48** [comment]
image
Am I doing something wrong? Or is the PR merged incorrectly?

**Comment by Fonceur** [comment]
> Am I doing something wrong? Or is the PR merged incorrectly?

Sounds like the issue I had when I forked it, try removing ZipArchive from that import and probably somewhere else...

**Comment by jhudsonWA** [comment]
The main project builds with or without the ZipArchive. As multiple people had issues I removed it and pushed it to a test branch. Please test if this branch fixes your issue (as I'm not getting it), and I can merge it in:  https://github.com/ZipArchive/ZipArchive/pull/611

**Comment by sweetppro** [comment]
> The main project builds with or without the ZipArchive. As multiple people had issues I removed it and pushed it to a test branch. Please test if this PR fixes your issue (as I'm not getting build errors), and I can merge it in: #611

thanks, its building fine for me now via SPM

**Pull request merged**
