### PR TITLE
fix compile errors for Xcode 10.2  and esp. Swift 5

### PR DESCRIPTION
**Pull request by DivineDominion**
Even though no Swift is used, the `SWIFT_VERSION` build setting caused the build tools to grind to a halt with the latest Xcode 10.2. I removed the offending setting and updated the project to conform to Xcode 10.2's new recommendations.

### CODE REVIEW

**Comment by jhudsonWA** [comment]
Thanks @DivineDominion  and @Coeur

**Comment by DivineDominion** [comment]
Great! Now that it's merged, will there be a point-release once the Travis build is functional again?

**Comment by Coeur** [comment]
@DivineDominion yes, in a few minutes/hours. I'm working on the travis builds first.

**Comment by DivineDominion** [comment]
@Coeur you're the best 🙌 thanks!

**Pull request merged**
