### PR TITLE
Matches different import modes

### PR DESCRIPTION
**Pull request by CLJian**
My project can not run. Import modes is not correct.

### CODE REVIEW

**Comment by BearRan** [comment]
Yep. I have the same problem.

**Comment by jhudsonWA** [comment]
How are you integrating this library into your project? Cocoapods? What version? 

Also what version of Xcode? 

Swift Project, or Pure Obj C? 

This is not a bad way to handle the includes, but I want to understand the different ways the project is used before we put in all of these workarounds.

2.4.1 was tested using a clean SPM test app, and a clean cocoapods test app before it was released (using the latest cocoapods), so I know they no longer step on each other with a standard configuration.

**Comment by jhudsonWA** [comment]
I'm going to merge this in as it should be harmless, but I still would like my questions answered so I know.

**Comment by jhudsonWA** [comment]
Pushed out and released as 2.4.2

**Comment by CLJian** [comment]
My project is Pure Obj C，using CocoaPods. The way you originally wrote it depends on the file path. With CocoaPods installation, the file path will disappear.

**Comment by jhudsonWA** [comment]
Thanks for the update, but I have a test pure obj c project using Cocoapods, that pulled down from 2.4.1 and it built fine. I did see that it flattened the folder structure but still built, so I figured we were golden. 

Anyway, thank you for the PR, I think we are stable now.

**Pull request merged**
