### PR TITLE
Minizip227

### PR DESCRIPTION
**Pull request by jhudsonWA**
Merge in Minizip 2 support (using compatibility layer). All tests pass now. Updating pod spec to version 3 just in case.

### CODE REVIEW

**Comment by jhudsonWA** [comment]
Control for AES/Password support is done through PREPROCESSOR flags in mini zip 2, updated the pod spec to set AES/ZLIB in the project files once installed

**Comment by jhudsonWA** [comment]
Still need a bit more work to have all CI builds complete. Seems broke in Xcode 8/7 due to: Include of non-modular header inside framework module

This could be fixed via a project setting but I'd rather project level setting changes not be required to use our library. I'll work on it more tomorrow. I downloaded Xcode 8 so I could test locally.

**Comment by jhudsonWA** [comment]
Ok, got CI builds to work. @Coeur could use some feedback/discussion on this topic. 

After migrating to minizip2 I replaced SSZipCommon.h with mz_compat.h as it included the typedef's that were in SSZipCommon.h, so seemed silly to have both

Once I did this I started getting the error: "include of non-modular header inside framework module" in Xcode 7 and 8. Xcode 9 was fine with this change. 

I set mz_compat.h as public so it was fine, but it also includes "zlib.h" which can't be made public resulting in the error. 

Solutions:

Add documentation that it would now be required to set CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES in main project to YES. This fixes the issue in Xcode 7/8. 

2) (current PR), bring back SSZipCommon.h, comment out the duplication typedef's in mz_compat.h, and include  SSZipCommon.h at the top of mz_compat.h and mz_compat.c. Issue here is that these changes would be required anytime minizip files are pulled in. 

Thoughts? Or previous experience that would help here?

**Comment by nmoinvaz** [comment]
@jhudsonWA - I have tried to fix the issue you were having from the minizip side with the headers.

**Comment by jhudsonWA** [comment]
Ok, I'll revisit and pull in the latest. Thanks!

**Comment by Coeur** [comment]
And I just noticed that @vszakats also made https://github.com/nmoinvaz/minizip/pull/252 in April, which are interesting compatibility changes that we should include in this pull request.

**Comment by Coeur** [comment]
@jhudsonWA time to look at this beast. Want to redo that yourself with latest minizip, or I give it a try myself?

**Comment by jhudsonWA** [comment]
Either way. I'm wrapping up a project, but could look within the next 10-14 days.

**Comment by Coeur** [comment]
Well, with the 1st of May coming, I have some free time. I'll give it a try.

**Comment by Coeur** [comment]
@jhudsonWA  I've attempted to solve the merge conflicts on this branch: https://github.com/ZipArchive/ZipArchive/tree/minizip286. Some tests pass, but not encryption, so some debugging needs to be done.

**Comment by Coeur** [comment]
Thank you for the work @jhudsonWA . I'll close this PR as it is now superseded by #509.

**Comment by Coeur** [comment]
@jhudsonWA I'll leave to you the deletion of this branch.

**Pull request closed without merging**
