### PR TITLE
replace kCFStringEncodingDOSLatinUS with NSUTF8StringEncoding

### PR DESCRIPTION
**Pull request by DkSuperMan**

### CODE REVIEW

**Comment by Coeur** [comment]
I assume you want to revert #443, considering the discussion at #449.

**Comment by Coeur** [comment]
Please provide a small sample archive that has the issue (ideally just a zero-bytes compressed file with problematic filename). Either as an attachment here or as a unit test.

**Comment by nmoinvaz** [comment]
Even though the specification says encoding is one way, some zip programs do not follow it. Some will use UTF-8 even though the UTF-8 flag is not set in the zip entry. The only thing you can probably count on is if the UTF-8 flag is set, it will be UTF-8 encoding, but if it is not set, then it could be anything. It might be best to default to UTF-8 but allow encoding to be configurable. It might reduce the number of GH issues about encoding problems.

**Comment by willson-chen** [comment]
#562 will be merged, so close this PR first.

**Pull request closed without merging**
