### PR TITLE
isPasswordValidForArchiveAtPath returning wrong result if first file is directory

### PR DESCRIPTION
**Pull request by 5b5**
Hi,

i suppose the method was not meant to exit with YES at this point but only when the while loop has finished? I recognized that the method did exit with YES even when the wrong or no password was given for password encrypted files, but only for some files. With this fix it works for my files. Maybe the assumptions in this part of the code are wrong? At least in my case it wasn't sufficient to test the first file though.

Cheers & thank you for your work!

### CODE REVIEW

**Comment by 5b5** [comment]
It turned out the problem occurs when the first file in the archive is an empty directory. The call to unzReadCurrentFile in this case will be given a len parameter of 0 which results in readBytes being 0 and the method returning YES.

**Comment by 5b5** [comment]
Tried to fix the problem by skipping over directories, i don't know enough about Zipfiles to be sure i didn't miss any cases. (i.e. is it 100% safe to read the filename and check for the ending character for each and every file?) Please review.

**Comment by 5b5** [comment]
Another solution might be just to check for readBytes > 0 ... 
``
if (readBytes < 0) {
  ...
  return NO; 
} else if (readBytes > 0) {
  return YES;
} else {
  // skip to next file
}
``

But i actually have no clue which of the solutions is more failsafe.

**Review by Coeur — DISMISSED** [review]
You're allocating filename, but you have some early returns which don't get call free(filename).

**Comment by Coeur** [comment]
Possible concerns:
* What if the first file is a zero-bytes file (and not a directory)?
* What about function `isFilePasswordProtectedAtPath`?

**Comment by 5b5** [comment]
Sorry, i must ask you for some patience, i will not be able to review your comments and respond for the next two weeks. I will try to respond asap thereafter.

**Comment by Coeur** [comment]
I've addressed the memory leak you had in filename, but it still leaves my other concerns.

**Comment by 5b5** [comment]
Thanks for fixing the memory issues!

I reproduced and tracked down the problem today, this is what i found:

1.) The problem is not reproducible in v2.1.4 because `unzOpenCurrentFilePassword` returns `UNZ_BADPASSWORD` now even for empty directories for files zipped with SSZipArchive, which means directories are skipped anyway (at least for files zipped with SSZipArchive, see 2.)). 

2.) The problem only occurred with zip files generated by SSZipArchive itself because with SSZipArchive (empty) directories zipped with password get the "flag & 1" set. Although i discovered, if zip files are created with the "zip" command, only files (not directories) seem to get this flag set.

Therefore, i'm not quite sure if the behavior described in 1.) is correct. For files zipped from command line `unzOpenCurrentFilePassword` still returns `UNZ_OK`, but the problem does not occur, as the flag is checked in `isPasswordValidForArchiveAtPath`, for `isFilePasswordProtectedAtPath` it doesn't matter, too.

I currently do have a zip file which reproduces the problem with v2.1.3 of SSZipArchive and added some test cases, but as the problem is gone now... do you still want those unit tests? I will push those testcases onto a new branch in my fork, if you want them i can add a new pull requests only containing the test cases...

**Comment by 5b5** [comment]
for unit tests and test files see https://github.com/5b5/ZipArchive/commit/2a4144cca2f3f9dce4da98038b91e993c2362809

If you think the behavior described in 1.) above is correct, please close this PR.

**Comment by Coeur** [comment]
I meant to add test cases if there was something broken in current version (2.1.4).

We should focus on attempting to make a legit password-protected archive with a different tool (comment line, WinZip, Keka, etc.) and some empty folders/files to see the password detection is working fine in all scenarios.

**Comment by 5b5** [comment]
As i described above, when a password-encrypted zip file is generated by SSZipArchive it will differ from an encrypted archive zipped from command line (even in 2.1.4) in having the encryption flag set on directory entries, whereas the flag is not set for directory entries in the file generated from command line.
(You can find such files in the commit mentioned above, you are welcome to use these files for you own tests, if you don't want to use my tests.)

I just wanted let you know that there is a difference in the results between both as i don't know which one is the right  method. (I had a look into the ZIP-Spec but i didn't find a clear answer and i am not at all familiar with the Zip-file format details.)

It MIGHT be a bug in the current version even if it doesn't lead to broken unit-tests as both files work together with `isPasswordValidForArchiveAtPath` because of different reasons:
The SSZipArchive-generated file works because `unzOpenCurrentFilePassword` returns `UNZ_BADPASSWORD` when providing a wrong password (which i also don't understand because a password should not be necessary in order to unzip a directory entry !?), the command line generated file returns `UNZ_OK` with a wrong password but skips on to the next entry because the encryption flag is not set.
So both files will work without problems but it still is unclear to me if setting the flag on directory entries while zipping is a bug or not.

I hope this made things a bit clearer. I cannot help you much further at the moment because i already spent about 7 hours on investigating this issue and i'm quite busy at the moment.

**Comment by Coeur** [comment]
I think this issue is still a valid concern.
I'll rebase it today to solve the conflict with #418, and then I'll add a test.

**Comment by Coeur** [comment]
I've verified that this test was previously failing before the fix.
Sorry for the long wait @5b5, but at last it's good to merge.

**Review by Coeur — APPROVED** [review]

**Comment by semvis123** [comment]
Hi, it seems like this is still an issue.
> Possible concerns:
> * What if the first item is a zero-bytes file (and not a directory)?

The `isPasswordValidForArchiveAtPath` returns `NO` for a zero byte file inside a zip, even with the correct password.

This seems to happen because of this check: https://github.com/ZipArchive/ZipArchive/blob/acc61be58181e635ae77718e66530b4ee7dea4be/SSZipArchive/SSZipArchive.m#L165

A corrected check would be `if (readBytes < 0 && fileInfo.uncompressed_size > 0)` but I'm unsure if this is correct for all archive types. (Is fileInfo.uncompressed_size always correct?)

**Pull request merged**
