### PR TITLE
commenting out unused code

### PR DESCRIPTION
**Pull request by Coeur**
Related issue: https://github.com/ZipArchive/ZipArchive/issues/201

### CODE REVIEW

**Comment by jhudsonWA** [comment]
Any votes for this one?

**Comment by Coeur** [comment]
My vote would be:
* to find a way to fix the unused symbolic link code in ZipArchive.m
* to find a way to retrieve the unused errors in zip.c

**Comment by jhudsonWA** [comment]
We try to not touch anything in the minizip folder if we can avoid it. It is directly from the zlib minizip source. In theory those bugs would be fixed up stream. So the question is how do we fix the issues in the main ZipArchive file. Any ideas besides comments?

**Comment by Coeur** [comment]
Can you provide a link to source zlib minizip so I can edit it?

**Comment by jhudsonWA** [comment]
http://www.winimage.com/zLibDll/minizip.html

I don't think they have a GitHub site.

**Comment by jhudsonWA** [comment]
Actually: this looks promising: 
https://github.com/nmoinvaz/minizip

**Pull request closed without merging**
