### PR TITLE
support aes,compatible old way for zip

### PR DESCRIPTION
**Pull request by jhudsonWA**
Recreates pull request #199

### CODE REVIEW

**Comment by DimonDeveloper** [comment]
Why don't you add this pull request to the project?

**Comment by jhudsonWA** [comment]
When I tried with #199, it caused errors in the example projects. Just need a bit more time to see if I can see why and then merge in the fix. Monday or Tuesday this should land.

**Comment by DimonDeveloper** [comment]
Good to know, thank you for your work and thank you for not throwing this project.

**Comment by jhudsonWA** [comment]
This support has landed. Will not update version or cocoapods until it passes all tests. One final test that is failing dealing with unzipping files that have bad header information. (#16)

**Pull request closed without merging**
