### PR TITLE
latest minizip

### PR DESCRIPTION
**Pull request by Coeur**
Latest https://github.com/nmoinvaz/minizip/ to get rid of Xcode warnings

This will need testing. :)
Also, considering the amount of changes, I suggest to change the version number of ZipArchive to 2.0.

### CODE REVIEW

**Comment by jhudsonWA** [comment]
I think I'll create a 2.0 branch and merge this in today and start testing.

Thanks!

**Comment by Coeur** [comment]
@jhudsonWA I'm concerned about my changes on SSZipCommon.h : I did it to avoid compilation errors with redefinitions of each typedef. But now, I start to wonder how people are going to use `+ (BOOL)unzipFileAtPath:(NSString *)path
    toDestination:(NSString *)destination
    progressHandler:(void (^)(NSString *entry, unz_file_info zipInfo, long entryNumber, long total))progressHandler
    completionHandler:(void (^)(NSString *path, BOOL succeeded, NSError * __nullable error))completionHandler;` if the details of `unz_file_info` are in a private header.

**Comment by jhudsonWA** [comment]
I didn't have time to dive into this today due to the keynote, but I'll take a look hopefully today. I have tests for all the methods and I can give it a try.

**Comment by Coeur** [comment]
The only warning left that I currently do not know how to fix properly is https://github.com/nmoinvaz/minizip/issues/115 in case you have time to tackle it.

**Comment by Coeur** [comment]
@jhudsonWA how was the keynote?.. note that you can get all the key slides from the videos of https://developer.apple.com/videos/wwdc2017/ by individually clicking "Resources" then "Presentation Slides (PDF)" to review those faster. ;)

And to make the Travis CI build succeed, there is a separate pull request that you can merge first.

**Comment by jhudsonWA** [comment]
Haha, I’m not still watching the keynote. Work project blew up. It ships early next week then I’ll have lots more time to dedicate to this. 😀

**Comment by Coeur** [comment]
Just for the joke: https://www.youtube.com/watch?v=wXLa5tprhLc

But *bad news*, I was right, `+unzipFileAtPath:toDestination:progressHandler:completionHandler:`, becomes unusable when `unz_file_info` is private, so I need to make further changes.

I use CocoaPods 1.2.1 to test with:

    pod 'SSZipArchive', :git => 'https://github.com/coeur/minizip.git', :branch => 'latest_minizip'

**Comment by jhudsonWA** [comment]
Thanks!

**Comment by Coeur** [comment]
I've modified unzip.h to include SSZipCommon.h as a workaround. @jhudsonWA can you test it? I think it works now.

**Comment by Coeur** [comment]
oh wait, I broke AES

**Comment by Coeur** [comment]
AES fixed. branch rebased.

**Comment by jhudsonWA** [comment]
Awesome. I should be able to test this weekend. Thanks so much @Coeur

**Comment by Coeur** [comment]
AES+Carthage fixed

**Comment by jhudsonWA** [comment]
You rock @Coeur. 👍 💯

**Comment by Coeur** [comment]
I'll fix the conflict and remove `requires_arc = true` later today.

**Comment by jhudsonWA** [comment]
Merging into a new 2.0 branch.

**Comment by jhudsonWA** [comment]
I'm going to check this out now and run it through some tests.

**Comment by jhudsonWA** [comment]
First tests look very promising. All our predefined tests passed. Getting an integer precision messages in SSZipArchive when testing with the ObjectiveCExample but besides that this looks good!

**Pull request merged**
