### PR TITLE
support for archiving symlinks

### PR DESCRIPTION
**Pull request by palmin**
I needed the ability to make archives containing symlinks and I have something working that could maybe be useful.

It definitely needs someone to give it a critical look, as I have only been a casual user of SSZipArchive.

The PR does 3 things:

1. Changes the VERSIONMADEBY macro to 3 which means Unix as opposed to MS-DOS. This is required for symlink flags to be respected and both iOS and macOS seem much closer to Unix than MS-DOS, but there could very well be side-effects to this change.

2. Adjusted the logic that enumerates a directory to look for files, directories and now symlinks in `createZipFileAtPath:...`

3. Made a new method to write symlinks:
`-writeSymlinkAtPath:withFilename:targetName:withPassword:`

### CODE REVIEW

**Comment by palmin** [comment]
I will find out why tests are failing and fix that. My guess is that file permissions need to be written in another way when the zip file has `VERSIONMADEBY=Unix`.

**Comment by jhudsonWA** [comment]
Is this PR ready for review?

**Comment by jhudsonWA** [comment]
After a quick look I worry about the change to SSZipArchive/minizip/zip.c as that should be done upstream https://github.com/coeur/minizip/

**Comment by Coeur** [comment]
Can you source to a documentation regarding the proposed value of VERSIONMADEBY?

**Comment by palmin** [comment]
@Coeur The justification for this is how SSZipArchive handles decoding symbolic links
    https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.m#L1007
that are only recognised when ``VERSIONMADEBY=Unix``.

Looking in http://www.pkware.com/documents/casestudies/APPNOTE.TXT section 4.4.2.2 there is 
``19 = OS X (Darwin)`` that is perhaps closer to the truth of how the library is used, but symbolic links would not be recognised.

**Comment by Coeur** [comment]
Thank you for the link to pkware.com. Now I understand better what this "version made by" is.

I'll spend some time to do various compatibility tests this weekend before changing anything.

**Comment by webjib** [comment]
In my own implementation (very similar to palmin one), I did not change `VERSIONMADEBY` for all files, but only when writing symlink file. Thus, I created a variant of `zipOpenNewFileInZip5` just for symlink.

Also, I did not use `[fileManager destinationOfSymbolicLinkAtPath:]` but a C function : `readlink` (but I guess the result is the same).

`len = readlink(path.fileSystemRepresentation, buffer, sizeof(buffer)-1);`

**Comment by palmin** [comment]
It sounds safer to only change `VERSIONMADEBY` when needed for symlinks. 

A difference between `destinationOfSymbolicLinkAtPath` and `readlink` might be that the later preserves whether links are relative or absolute. Much of the work to *fix* links before writing them would maybe not be required if `readlink` as used instead.

There is some logic where symlinks leaving the zip file are not written that is partly that way because there is no way to calculate the relative symlink. 
https://github.com/palmin/ZipArchive/blob/0ec89cbc477be081bc83c9b1a14a482e68e54869/SSZipArchive/SSZipArchive.m#L733

Should I try to adjust to do like @webjib for `VERSIONMADEBY` and to use `readlink`?

**Comment by webjib** [comment]
Yes, you're right, in my tests, `readlink` is preserving relative path for symlink, so it's better to use it. For testing purpose only, I subclassed `SSZipArchive` but what bothered me is that I needed to alter mini zip files (as jhudsonWA stated above)...

PS:  SSZipArchive is not totally "subclass-ready"

**Comment by palmin** [comment]
I made these changes in another branch to not keep changing this PR. 

    https://github.com/palmin/ZipArchive/tree/another-try
I will merge them in if there is consensus that this is a good idea.

Changing such that `VERSIONMADEBY` is only `Unix` is made such that there are no changes to `minizip` and that is nice as it removes to the need for upstream changes. Avoiding this required me to define a external declaration of `zipOpenNewFileInZip_internal` in `SSZipArchive` which seems like violating encapsulation. 

I'm not sure I like it very much. Suggestions on other ways to achieve this are very welcome.

The other change to use `readlink` is much nicer.

**Comment by Coeur** [comment]
webjib suggestion to only change VERSIONMADEBY when needed sounds better.
As for `readlink`, it sounds nice. I wonder if it is compatible for both iOS and macOS, APFS and HFS+, but I hope it is.

**Comment by palmin** [comment]
It absolutely sounds better to only change `VERSIONMADEBY` when needed. 

My question is how important it is to avoid changes to `minizip`. Watch how this requires me to define `zipOpenNewFileInZip_internal` as I have found no non-internal function that lets us control `version_madeby`.


````int _zipOpenEntryUnix(zipFile entry, NSString *name, const zip_fileinfo *zipfi, int level, NSString *password, BOOL aes) {
    
    extern int ZEXPORT zipOpenNewFileInZip_internal(zipFile file,
                                                    const char *filename,
                                                    const zip_fileinfo *zipfi,
                                                    const void *extrafield_local,
                                                    uint16_t size_extrafield_local,
                                                    const void *extrafield_global,
                                                    uint16_t size_extrafield_global,
                                                    const char *comment,
                                                    uint16_t flag_base,
                                                    int zip64,
                                                    uint16_t method,
                                                    int level,
                                                    int raw,
                                                    int windowBits,
                                                    int memLevel,
                                                    int strategy,
                                                    const char *password,
                                                    int aes,
                                                    uint16_t version_madeby);
    
    zipFile file = entry;
    const char *filename = name.fileSystemRepresentation;
    const void *extrafield_local = NULL;
    uint16_t size_extrafield_local = 0;
    const void *extrafield_global = NULL;
    uint16_t size_extrafield_global = 0;
    const char *comment = NULL;
    uint16_t flag_base = 0;
    int zip64 = 0;
    uint16_t method = Z_DEFLATED;
    int raw = 0;
    int windowBits = -MAX_WBITS;
    int memLevel = DEF_MEM_LEVEL;
    int strategy = Z_DEFAULT_STRATEGY;
    
    // field is described in http://www.pkware.com/documents/casestudies/APPNOTE.TXT section 4.4.2.2
    int version_madeby = (3 << 8);

    
    return zipOpenNewFileInZip_internal(file, filename, zipfi, extrafield_local, size_extrafield_local,
                                        extrafield_global, size_extrafield_global, comment, flag_base,
                                        zip64, method, level, raw, windowBits, memLevel, strategy,
                                        password.UTF8String, aes, version_madeby);
}````

To avoid changing `minizip` something that is internal is used from the outside and if this ever changes in `minizip` it will be a headache for `SSZipArchive`. 

I suggest accepting changes to `minizip` and adding a variant of `zipOpenNewFileInZip5` with a `version_madeby` parameter.

**Comment by webjib** [comment]
@Coeur : I've tested only on macOS with AFPS for the moment and it works perfectly. 

@palmin : I did exactly like you, adding a variant of `zipOpenNewFileInZip5` in zip.c

**Comment by Coeur** [comment]
For the record, @palmin and @webjib, `zipOpenNewFileInZip5` was added by me to minizip a month ago: https://github.com/Coeur/minizip/blame/master/zip.h

At that time, I did not include `version_madeby` because I did not understood there was a use for it. But I'm totally OK to directly modify the signature of `zipOpenNewFileInZip5` without creating a variant as [my fork](https://github.com/Coeur/minizip) has basically 0 stars, so it's unlikely that anyone has been using it except ZipArchive itself.

**Comment by webjib** [comment]
@coeur : did not know that, so that's perfect if you can adjust `zipOpenNewFileInZip5` !

**Comment by palmin** [comment]
@Coeur Great. If you let me know when `zipOpenNewFileInZip5` is updated, I will make adjustments to this PR that take this into account.

**Comment by webjib** [comment]
@palmin you need to move `readlink` procedure to `writeSymlinkAtPath:` because one could want to use this function directly (me, for example). I don't use `createZipFileAtPath:` because I need a particular implementation when zipping (and SSZipArchive is built to either using createZipFileAtPath: or functions directly).

**Comment by palmin** [comment]
@webjib I moved the logic as requested and this also uses `readlink` instead of ?`destinationOfSymbolicLinkAtPath`.

PR is not yet ready for review through, as I am waiting for the minizip change before writing different `version_madeby` for links and non-links.

**Comment by webjib** [comment]
@palmin be careful, in your last change, your writing incorrect buffer in  `zipWriteInFileInZip(_zip, buffer, (uint32_t)strlen(buffer));` (you should write linktarget, instead you're writing filename)

**Comment by palmin** [comment]
@webjib Thank you for spotting this. Tests passing made me complacent.

**Comment by Coeur** [comment]
Thank you. Allow me 24 hours, or make a PR on coeur/minizip. :)

**Comment by Coeur** [comment]
@palmin I made a minor change on minizip to allow customizing version_madeby.

**Comment by palmin** [comment]
Tests failed on xcode 8.3 simulator and it looks like tests did not even run.
  https://travis-ci.org/ZipArchive/ZipArchive/jobs/305662793#L887

Any suggestions on how to proceed?

**Comment by Coeur** [comment]
No worry. You can eventually re-run test 362.10 by identifying yourself with Travis. It's not blocking me from reviewing and eventually merge. :)

**Comment by jhudsonWA** [comment]
I'll take a look at this after the holidays Just want to let you know you were not forgotten. Thanks for the PR.

**Pull request closed without merging**
