### PR TITLE
Mac target added

### PR DESCRIPTION
**Pull request by kylejm**
Fixes issue #226. Builds on top of #222.

To use this change until it is reviewed:
```
github "LootApp/ZipArchive" "mac-target"
```

### CODE REVIEW

**Comment by jhudsonWA** [comment]
Merged into master. Please test with Carthage.

**Comment by kylejm** [comment]
Awesome! Tested and works great!

To speed up CI builds, please could you attached a framework archive to the GitHub release tag?

It's easy to make one using Carthage:

```bash
$ carthage build --no-skip-current --platform mac
```

```bash
$ carthage archive ZipArchive
```

**Comment by kylejm** [comment]
Also can you make a new release so that Carthage can pick these fixes up?

A workaround for anyone else in the meantime is to change your `ZipArchive` dependancy in your `Cartfile` to look like this:

```
github "ZipArchive/ZipArchive" "master"
```
**Caution** :warning::  this doesn't use a released version

**Comment by jhudsonWA** [comment]
Yep, let me do a bit more testing and I'll try to this week

**Comment by jhudsonWA** [comment]
Ok, latest version released. You should be able to switch away from master now. Thanks @kylejm!

**Comment by kylejm** [comment]
No problem! :smile: 

Will you be adding a framework archive to the release soon too?

**Comment by jhudsonWA** [comment]
uh.. how do I do that for Carthage. The problem is I don't use it... :)

**Comment by jhudsonWA** [comment]
Is it this? Archive prebuilt frameworks into one zip file

Carthage can automatically use prebuilt frameworks, instead of building from scratch, if they are attached to a GitHub Release on your project’s repository.

To offer prebuilt frameworks for a specific tag, the binaries for all supported platforms should be zipped up together into one archive, and that archive should be attached to a published Release corresponding to that tag. The attachment should include .framework in its name (e.g., ReactiveCocoa.framework.zip), to indicate to Carthage that it contains binaries.

You can perform the archiving operation above with the carthage archive command as follows:

carthage build --no-skip-current
carthage archive YourFrameworkName

**Comment by jhudsonWA** [comment]
I think it's now done ;) Let me know if it works.

**Comment by kylejm** [comment]
Works a treat! Thank you! :grin:

**Comment by jhudsonWA** [comment]
Great!

**Comment by Coeur** [comment]
@kylejm can you clarify if dsym files are needed for the CI builds?
In the latest release of ZipArchive, I've removed the dsym as they take quite some space, but if they are needed in the process of CI testing, then it would be best to know.

**Comment by kylejm** [comment]
@Coeur AFAIK you don't _need_ them for CI, although they're of course very useful for debugging crashes.

**Comment by Coeur** [comment]
OK @kylejm, then I'll keep the attached framework archive free of dsym files to make it smaller and faster to download.
If you get a crash in one of your CI test, I can imagine that you'll re-run the specific test locally with a complete Carthage installation.

**Comment by kylejm** [comment]
@Coeur ahhhh, okay. It's standard practice to strip symbols from release builds, so that's fine. But on the CI, you usually test in a Debug config, meaning you'll have the symbol information. It's really handy and speeds you up by just looking on the CI for the failure.

**Pull request merged**
